### ISSUE TITLE
Stuck on connected on Linux

### ISSUE THREAD

**Issue by sergio-ivanuzzo** [fotcorn/pywowd#1]
Hello, I'm running your server, but when I'm trying to connect (set realmlist localhost) client stucks on 'Connected'. How this can be fixed ? I've tried to debug via wireshark - client do not respond after SMSG_AUTH_RESPONSE

**Comment by fotcorn** [comment]
What version of WoW are you using? I think the only one that ever worked was the master branch with Wotlk 3.3.5.

**Comment by sergio-ivanuzzo** [comment]
I'm using 2.4.3. Does it have any differencies in the authentication? Comparing with wotlk

**Comment by fotcorn** [comment]
Yes, everything is completely different. Event between 3.3.4 and 3.3.5, all ids/opcodes in the network packages are randomized by blizzard to make it more difficult to write hacks/emulators.

**Comment by sergio-ivanuzzo** [comment]
Can you please help me to debug, why client stucks on Connected? This is my project: https://github.com/sergio-ivanuzzo/wowcore

**Comment by fotcorn** [comment]
I dont really have time to help you, sorry. What I did back when I wrote this is running Mangos (https://www.getmangos.eu/downloads/category/2-mangos-one/) and checking with Wireshark what packets were sent. Or you can try to modify Mangos to print all sent/received packets, this way you can see the unencrypted data.
